# AutoViaUpdater config
# For understanding difference between dev and normal builds visit here: https://ci.viaversion.com/
# Default builds when enabled are normal builds, but you can explicitly make it dev builds

# Check-Interval setting
# The interval (in minutes) to check for updates
Check-Interval = 60

# The number of seconds to wait after the server has fully loaded before starting the update checking process.
# Setting this value too low may cause errors.
# If errors occur while loading vias, try setting this value to 60 seconds or higher.
Delay = 5

[ViaVersion]
# Enable or disable ViaVersion updates
enabled = true
# Enable or disable dev.
dev = false

[ViaBackwards]
# Enable or disable ViaBackwards updates
enabled = true
# Enable or disable dev.
dev = false

[ViaRewind]
# Enable or disable ViaRewind updates
enabled = true
# Enable or disable dev.
dev = false

[ViaRewind-Legacy]
# Enable or disable ViaRewind-Legacy updates. Note: Will not do anything for Bungeecord
enabled = true