# AutoViaUpdater config
# For understanding the difference between release and snapshot builds visit: https://ci.viaversion.com/
# 'snapshot' chooses latest builds when available regardless if they are -SNAPSHOT or not; otherwise latest non-snapshot is used.
# 'dev' selects the *-DEV* Jenkins job; 'java8' selects the *-Java8* job.
# All of the builds here are from Jenkins. If you want to use any other source use this plugin: https://www.spigotmc.org/resources/autoupdateplugins.109683/

# Check-Interval setting
# The interval (in minutes) to check for updates
Check-Interval = 60

# Experimental Cron Support
# Example "0 0 * * *" is daily at midnight
# Leave it blank "" to disable and use the Check-Interval
Cron-Expression = ""

# The number of seconds to wait after the server has fully loaded before starting the update checking process.
# Setting this value too low may cause errors.
# If errors occur while loading vias, try setting this value to 60 seconds or higher.
Delay = 5

# AutoRestart settings
# AutoRestart is whether or not the server will restart after an update
# AutoRestart-Delay is the delay in seconds before restarting
# AutoRestart-Message is the message that will be broadcasted before restarting
AutoRestart = false
AutoRestart-Delay = 60
AutoRestart-Message = '&cServer is restarting in 1 minute!'

[ViaVersion]
# Enable or disable ViaVersion updates (https://ci.viaversion.com/job/ViaVersion)
enabled = true
# Download the latest build, regardless of whether it's a snapshot "-SNAPSHOT" or not.
# Otherwise, download the latest non-snapshot build.
snapshot = true
# Enable or disable DEV channel builds from Jenkins
dev = false
# Enable or disable Java 8 builds (https://ci.viaversion.com/job/ViaVersion-Java8/)
java8 = false

[ViaBackwards]
# Enable or disable ViaBackwards updates (https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards/)
enabled = true
# Download the latest build, regardless of whether it's a snapshot "-SNAPSHOT" or not.
# Otherwise, download the latest non-snapshot build.
snapshot = true
# Enable or disable DEV channel builds from Jenkins
dev = false
# Enable or disable Java 8 builds (https://ci.viaversion.com/view/ViaBackwards/job/ViaBackwards-Java8/)
java8 = false

[ViaRewind]
# Enable or disable ViaRewind updates (https://ci.viaversion.com/view/ViaRewind/job/ViaRewind/)
enabled = true
# Download the latest build, regardless of whether it's a snapshot "-SNAPSHOT" or not.
# Otherwise, download the latest non-snapshot build.
snapshot = true
# Enable or disable DEV channel builds from Jenkins
dev = false
# Enable or disable Java 8 builds (https://ci.viaversion.com/view/ViaRewind/job/ViaRewind-Java8/)
java8 = false

[ViaRewind-Legacy]
# Enable or disable ViaRewind-Legacy updates. Note: Will not do anything for Bungeecord servers. (https://ci.viaversion.com/view/ViaRewind/job/ViaRewind%20Legacy%20Support/)
enabled = true
# Download the latest build, regardless of whether it's a snapshot "-SNAPSHOT" or not.
# Otherwise, download the latest non-snapshot build.
snapshot = true
# Enable or disable DEV channel builds from Jenkins
dev = false
