# AutoViaUpdater config
# For understanding difference between dev and normal builds visit here: https://ci.viaversion.com/
# Default builds when enabled are normal builds, but you can explicitly make it dev builds

# Check-Interval setting
# The interval (in minutes) to check for updates
Check-Interval = 60

[ViaVersion]
# Enable or disable ViaVersion updates
enabled = true
# Enable or disable dev.
dev = false

[ViaBackwards]
# Enable or disable ViaBackwards updates
enabled = true
# Enable or disable dev.
dev = false

[ViaRewind]
# Enable or disable ViaRewind updates
enabled = true
# Enable or disable dev.
dev = false

[ViaRewind-Legacy]
# Enable or disable ViaRewind-Legacy updates. Note: Will not do anything for Bungeecord
enabled = true