name: AutoViaUpdater
version: 8.0
main: spigot.AutoViaUpdater
authors:
  - NewAmazingPVP
description: AutoViaUpdater is a Spigot/BungeeCord plugin that automates the updating of Vias like ViaVersion, ViaRewind, ViaBackwards, and ViaRewind-Legacy.
commands:
  updatevias:
    description: Force update checker for all vias!
    usage: /updatevias
    permission: autoviaupdater.admin
    default: op
softdepend:
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - ViaRewind-Legacy-Support