name: AutoViaUpdater
version: 10.0.0
main: spigot.AutoViaUpdater
api-version: 1.13
folia-supported: true
authors:
  - NewAmazingPVP
description: AutoViaUpdater is a Spigot/BungeeCord plugin that automates the updating of Vias like ViaVersion, ViaRewind, ViaBackwards, and ViaRewind-Legacy.
commands:
  updatevias:
    description: Force update checker for all vias!
    usage: /updatevias
    permission: autoviaupdater.admin
permissions:
  autoviaupdater.admin:
    description: Allows using /updatevias and automatic update checks
    default: op
softdepend:
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - ViaRewind-Legacy-Support
