name: AutoViaUpdater
version: 1.0
main: newamazingpvp.autoviaupdater.AutoViaUpdater
authors: NewAmazingPVP
description: AutoViaUpdater is a Spigot/BungeeCord plugin that automates the updating of Vias like ViaVersion, ViaRewind, ViaBackwards, and ViaRewind-Legacy.
