name: AutoViaUpdater
version: 9.5.1
main: spigot.AutoViaUpdater
api-version: 1.13
# hackfix (definitely will not work as intended)
folia-supported: true
authors:
  - NewAmazingPVP
description: AutoViaUpdater is a Spigot/BungeeCord plugin that automates the updating of Vias like ViaVersion, ViaRewind, ViaBackwards, and ViaRewind-Legacy.
commands:
  updatevias:
    description: Force update checker for all vias!
    usage: /updatevias
    permission: autoviaupdater.admin
    default: op
softdepend:
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - ViaRewind-Legacy-Support