name: AutoViaUpdater
version: 3.5
main: spigot.AutoViaUpdater
authors:
  - NewAmazingPVP
description: AutoViaUpdater is a Spigot/BungeeCord plugin that automates the updating of Vias like ViaVersion, ViaRewind, ViaBackwards, and ViaRewind-Legacy.
